name: pdfjimmy
description: "A new Flutter project."
publish_to: "none"
version: 1.0.7+7

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: any
  syncfusion_flutter_pdfviewer: ^27.1.48
  syncfusion_flutter_pdf: ^27.1.48
  path_provider: ^2.1.5
  file_picker: any

  google_fonts: ^6.3.2

  flutter_colorpicker: any

  translator: ^1.0.4+1
  image_picker: ^1.2.1
  speech_to_text: ^7.1.0
  flutter_tts: any
  get_storage: any
  http: any
  sqflite: any
  provider: ^6.1.5
  share_plus: any
  url_launcher: any
  permission_handler: ^12.0.1
  path: ^1.9.1
  signature: ^5.4.0
  crypto: ^3.0.3
  uuid: any
  crop_your_image: ^2.0.0
  image: ^4.0.0

  printing: ^5.13.4
  pdf: ^3.11.1

  google_mlkit_document_scanner: ^0.2.0
  google_mlkit_text_recognition: ^0.15.1
  gap: ^3.0.1
  flutter_secure_storage: ^10.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  sqflite_common_ffi: ^2.3.6
  camera: ^0.11.2+1
  flutter_animate: ^4.5.2
  reorderable_grid_view: ^2.2.8
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:

    - assets/pdfjimmy_icon.png

flutter_launcher_icons:
  image_path: "assets/pdfjimmy_icon.png"
  android: true
  ios: true
