import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfBuilder {
  /// Creates a PDF from a list of image paths.
  /// [imagePaths]: List of absolute paths to images.
  /// [outputPath]: Absolute path where the PDF should be saved.
  static Future<File> createPdfFromImages({
    required List<String> imagePaths,
    required String outputPath,
    List<String>? extractedText,
  }) async {
    final pdf = pw.Document();

    // AI Feature 1: "Smart Summary" Page (Overview)
    // If text exists, let's create a cover page with key insights.
    if (extractedText != null && extractedText.any((t) => t.isNotEmpty)) {
      // Basic extraction of 'Money' and 'Dates' for the summary
      final allText = extractedText.join('\n');
      final amounts = RegExp(
        r'[\$€£₹]\s?\d+(?:,\d{3})*(?:\.\d{2})?',
      ).allMatches(allText).map((m) => m.group(0)).toSet().take(5).join(', ');
      final emails = RegExp(
        r'\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b',
      ).allMatches(allText).map((m) => m.group(0)).toSet().join(', ');

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Header(level: 0, child: pw.Text("AI Document Summary")),
                pw.SizedBox(height: 20),
                pw.Text(
                  "Overview",
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 16,
                  ),
                ),
                pw.Divider(),
                pw.SizedBox(height: 10),
                if (amounts.isNotEmpty) pw.Text("Financials: $amounts"),
                if (emails.isNotEmpty) pw.Text("Contacts: $emails"),
                pw.SizedBox(height: 20),
                pw.Text(
                  "Generated by pdfjimmy AI",
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey,
                  ),
                ),
              ],
            );
          },
        ),
      );
    }

    // Original Images
    for (final path in imagePaths) {
      final file = File(path);
      if (!file.existsSync()) continue;

      // Read image bytes
      final imageBytes = await file.readAsBytes();
      final image = pw.MemoryImage(imageBytes);

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(0),
          build: (pw.Context context) {
            return pw.Center(child: pw.Image(image, fit: pw.BoxFit.contain));
          },
        ),
      );
    }

    // AI Feature: Add a "Text Transcript" (OCR Result) at the end of the PDF
    if (extractedText != null && extractedText.any((t) => t.isNotEmpty)) {
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Header(
                  level: 0,
                  child: pw.Text("AI Transcript (Searchable Text)"),
                ),
                pw.SizedBox(height: 10),
                ...extractedText.map((text) {
                  if (text.isEmpty) return pw.Container();
                  return pw.Padding(
                    padding: const pw.EdgeInsets.only(bottom: 10),
                    child: pw.Text(
                      text,
                      style: const pw.TextStyle(fontSize: 10),
                    ),
                  );
                }).toList(),
              ],
            );
          },
        ),
      );
    }

    final outputFile = File(outputPath);
    await outputFile.writeAsBytes(await pdf.save());
    return outputFile;
  }
}
